version: '3.8'
# networks:
#   go_train_network:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 127.0.0.1/24
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/go/src/gobe/
    depends_on:
      - database
  database:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
volumes:
  dbdata:
