version: '3.8'
# networks:
#   go_train_network:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 1.0.4.0/24
services:
  # backend:
  #   container_name: backend
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/go/src/gobe/
  #   depends_on:
  #     - database
    # networks:
    #   - go_train_network
  database:
    image: postgres:12
    container_name: database
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    # expose:
    #   - 5432
    ports:
      - 5432:5432
    # networks:
    #   - go_train_network
volumes:
  dbdata:
