version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
volumes:
  dbdata:
